version: 2

project_name: crv

before:
  hooks:
    - go mod tidy

builds:
  - id: crv
    main: ./cmd/crv
    binary: crv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    ids:
      - crv
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

brews:
  - name: crv
    ids:
      - default
    repository:
      owner: izuno4t
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/izuno4t/coverage-report-viewer-cli
    description: Coverage report viewer for terminals
    license: MIT
    test: |
      system "#{bin}/crv", "--version"

release:
  draft: false
  prerelease: auto
